name: Deploy with AWS Copilot

on:
  push:
    branches:
      - main  # Deploy only on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install AWS Copilot CLI
        run: |
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot
          sudo mv copilot /usr/local/bin/

      - name: Deploy to AWS ECS (Test)
        run: |
          copilot deploy --env test

      - name: Deploy to AWS ECS (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          copilot deploy --env production
